# Generated by Django 4.1.2 on 2022-10-06 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pubs'),
            preserve_default=False,
        ),
    ]
